--{{{ AiStateList
--- @class AiStateList
local AiStateList = {
	avoidInfernos = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateAvoidInfernos",
	boost = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateBoost",
	check = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateCheck",
	chickenInteraction = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateChickenInteraction",
	defend = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateDefend",
	defendHostageCarrier = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateDefendHostageCarrier",
	defuse = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateDefuse",
	developer = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateDeveloper",
	drop = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateDrop",
	engage = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateEngage",
	evacuate = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateEvacuate",
	evade = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateEvade",
	flashbangDynamic = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateFlashbangDynamic",
	follow = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateFollow",
	freezetime = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateFreezetime",
	graffiti = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateGraffiti",
	heGrenade = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateHeGrenade",
	idle = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateIdle",
	knife = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateKnife",
	lurkWithBomb = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateLurkWithBomb",
	molotov = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateMolotov",
	patrol = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePatrol",
	pickupBomb = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePickupBomb",
	pickupItems = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePickupItems",
	plant = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePlant",
	pushDemolition = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePushDemolition",
	pushHostage = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStatePushHostage",
	rescueHostage = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateRescueHostage",
	rotate = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateRotate",
	smoke = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateSmoke",
	sweep = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateSweep",
	trafficControl = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateTrafficControl",
	wait = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateWait",
	watch = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateWatch",
	zombie = require "gamesense/Nyx/v1/Dominion/Ai/State/AiStateZombie",
}

return AiStateList
--}}}
