--{{{ AiChatCommand
--- @class AiChatCommand
local AiChatCommand = {
	afk = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandAfk",
	ai = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandToggleAi",
	aim = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandAim",
	assist = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandAssist",
	bomb = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandBomb",
	boost = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandBoost",
	bt = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandBacktrack",
	buy = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandBuy",
	chat = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandChat",
	cmd = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandCmd",
	dc = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandDisconnect",
	drop = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandDrop",
	e = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandEval",
	eco = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandEco",
	follow = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandFollow",
	force = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandForce",
	go = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandGo",
	kill = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandKill",
	knife = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandKnife",
	know = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandKnow",
	log = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandLog",
	mecon = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandManageEconomy",
	noise = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandNoise",
	ok = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandOk",
	rboost = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandRunBoost",
	reload = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandReload",
	report = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandReport",
	rot = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandRotate",
	rush = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandRush",
	save = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandSave",
	scramble = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandScramble",
	skill = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandSkill",
	skipmatch = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandSkipMatch",
	stop = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandStop",
	tag = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandClantag",
	thanks = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandThanks",
	vote = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandVote",
	wait = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandWait",
	zombie = require "gamesense/Nyx/v1/Dominion/Ai/ChatCommand/AiChatCommandZombie",
}

return AiChatCommand
--}}}
