--{{{ Dependencies
local Nyx = require "gamesense/Nyx/v1/Api/Nyx"
--}}}

--{{{ Performance
--- @class Performance : Class
local Performance = {}

--- @return void
function Performance.enable()
    cvar.cl_autohelp:set_raw_int(0)
    cvar.cl_disable_ragdolls:set_raw_int(1)
    cvar.cl_disablefreezecam:set_raw_int(1)
    cvar.cl_disablehtmlmotd:set_raw_int(1)
    cvar.cl_drawshadowtexture:set_raw_int(0)
    cvar.cl_ejectbrass:set_raw_int(0)
    cvar.cl_freezecameffects_showholiday:set_raw_int(0)
    cvar.cl_particle_fallback_base:set_raw_int(0)
    cvar.cl_particle_fallback_multiplier:set_raw_int(0)
    cvar.cl_predict:set_raw_int(1)
    cvar.cl_ragdoll_collide:set_raw_int(0)
    cvar.cl_ragdoll_self_collision:set_raw_int(0)
    cvar.cl_show_splashes:set_raw_int(0)
    cvar.cl_showhelp:set_raw_int(0)
    cvar.cl_showpos:set_raw_int(0)
    cvar.cl_smooth:set_raw_int(0)
    cvar.fog_enable:set_raw_int(0)
    cvar.fog_enable_water_fog:set_raw_int(0)
    cvar.fog_enableskybox:set_raw_int(0)
    cvar.fog_enableskybox:set_raw_int(1)
    cvar.func_break_max_pieces:set_raw_int(0)
    cvar.gameinstructor_enable:set_raw_int(0)
    cvar.mat_bloomscale:set_raw_int(0)
    cvar.mat_bumpmap:set_raw_int(0)
    cvar.mat_colorcorrection:set_raw_int(0)
    cvar.mat_depthbias_shadowmap:set_raw_int(0)
    cvar.mat_depthfeather_enable:set_raw_int(0)
    cvar.mat_disable_bloom:set_raw_int(1)
    cvar.mat_disable_fancy_blending:set_raw_int(1)
    cvar.mat_displacementmap:set_raw_int(0)
    cvar.mat_dof_enabled:set_raw_int(0)
    cvar.mat_dof_max_blur_radius:set_raw_int(0)
    cvar.mat_dof_quality:set_raw_int(0)
    cvar.mat_drawwater:set_raw_int(0)
    cvar.mat_dynamic_tonemapping:set_raw_int(0)
    cvar.mat_fastclip:set_raw_int(1)
    cvar.mat_fastnobump:set_raw_int(1)
    cvar.mat_fastspecular:set_raw_int(1)
    cvar.mat_filtertextures:set_raw_int(1)
    cvar.mat_force_bloom:set_raw_int(0)
    cvar.mat_hdr_enabled:set_raw_int(0)
    cvar.mat_loadtextures:set_raw_int(0)
    cvar.mat_motion_blur_enabled:set_raw_int(0)
    cvar.mat_reducefillrate:set_raw_int(1)
    cvar.mat_reduceparticles:set_raw_int(1)
    cvar.mat_shadercount:set_raw_int(0)
    cvar.mat_shadowstate:set_raw_int(0)
    cvar.mat_specular:set_raw_int(0)
    cvar.r_decals:set_raw_int(0)
    cvar.r_DrawDisp:set_raw_int(0)
    cvar.r_drawflecks:set_raw_int(0)
    cvar.r_drawsprites:set_raw_int(0)
    cvar.r_drawtracers_firstperson:set_raw_int(0)
    cvar.r_drawviewmodel:set_raw_int(0)
    cvar.r_dynamic:set_raw_int(0)
    cvar.r_dynamiclighting:set_raw_int(0)
    cvar.r_fastzreject:set_raw_int(0)
    cvar.r_jiggle_bones:set_raw_int(0)
    cvar.r_lightmap:set_raw_int(0)
    cvar.r_lightstyle:set_raw_int(0)
    cvar.r_rimlight:set_raw_int(0)
    cvar.r_rimlight:set_raw_int(0)
    cvar.r_shadowmaxrendered:set_raw_int(0)
    cvar.r_shadowrendertotexture:set_raw_int(0)
    cvar.r_shadows:set_raw_int(0)
    cvar.r_sse_s:set_raw_int(0)
    cvar.r_updaterefracttexture:set_raw_int(0)
    cvar.r_waterdrawreflection:set_raw_int(0)
    cvar.r_waterdrawrefraction:set_raw_int(0)
    cvar.r_waterforceexpensive:set_raw_int(0)
    cvar.r_waterforcereflectentities:set_raw_int(0)
    cvar.violence_ablood:set_raw_int(0)
    cvar.violence_hblood:set_raw_int(0)
end

return Nyx.class("Performance", Performance)
--}}}
